import ServerComponent from "@/components/ServerComponent";
export default function League() {
  return (
    <>
      <ServerComponent
        teamName="barcelona"
        teamId={2817}
        tournamentId={8}
        seasonId={77559}
      />
      <ServerComponent
        teamName="mancity"
        teamId={17}
        tournamentId={17}
        seasonId={76986}
      />
      <ServerComponent
        teamName="liverpool"
        teamId={44}
        tournamentId={17}
        seasonId={76986}
      />
      <ServerComponent
        teamName="realmadrid"
        teamId={2829}
        tournamentId={8}
        seasonId={77559}
      />
      <ServerComponent
        teamName="atmadrid"
        teamId={2836}
        tournamentId={8}
        seasonId={77559}
      />
      <ServerComponent
        teamName="inter"
        teamId={2697}
        tournamentId={23}
        seasonId={76457}
      />
      <ServerComponent
        teamName="milan"
        teamId={2692}
        tournamentId={23}
        seasonId={76457}
      />

      <ServerComponent
        teamName="juventus"
        teamId={2687}
        tournamentId={23}
        seasonId={76457}
      />
      <ServerComponent
        teamName="arsenal"
        teamId={42}
        tournamentId={17}
        seasonId={76986}
      />
      <ServerComponent
        teamName="manutd"
        teamId={35}
        tournamentId={17}
        seasonId={76986}
      />
      <ServerComponent
        teamName="chelsea"
        teamId={38}
        tournamentId={17}
        seasonId={76986}
      />
      <ServerComponent
        teamName="psg"
        teamId={1644}
        tournamentId={34}
        seasonId={77356}
      />
      <ServerComponent
        teamName="bayern"
        teamId={2672}
        tournamentId={35}
        seasonId={77333}
      />
      <ServerComponent
        teamName="dortmund"
        teamId={2673}
        tournamentId={35}
        seasonId={77333}
      />
      <ServerComponent
        teamName="bayer"
        teamId={2681}
        tournamentId={35}
        seasonId={77333}
      />
      <ServerComponent
        teamName="newcastle"
        teamId={39}
        tournamentId={17}
        seasonId={76986}
      />

      <ServerComponent
        teamName="lazio"
        teamId={2699}
        tournamentId={23}
        seasonId={76457}
      />

      <ServerComponent
        teamName="atalanta"
        teamId={2686}
        tournamentId={23}
        seasonId={76457}
      />
      <ServerComponent
        teamName="napoli"
        teamId={2714}
        tournamentId={23}
        seasonId={76457}
      />

      <ServerComponent
        teamName="atbilbao"
        teamId={2825}
        tournamentId={8}
        seasonId={77559}
      />
    </>
  );
}
