import ServerComponent from "@/components/ServerComponent";
export default function League() {
  return (
    <>
      <ServerComponent
        teamName="barcelona"
        teamId={2817}
        tournamentId={8}
        seasonId={61643}
      />
      <ServerComponent
        teamName="mancity"
        teamId={17}
        tournamentId={17}
        seasonId={61627}
      />
      <ServerComponent
        teamName="liverpool"
        teamId={44}
        tournamentId={17}
        seasonId={61627}
      />
      <ServerComponent
        teamName="realmadrid"
        teamId={2829}
        tournamentId={8}
        seasonId={61643}
      />
      <ServerComponent
        teamName="atmadrid"
        teamId={2836}
        tournamentId={8}
        seasonId={61643}
      />
      <ServerComponent
        teamName="inter"
        teamId={2697}
        tournamentId={23}
        seasonId={63515}
      />
      <ServerComponent
        teamName="milan"
        teamId={2692}
        tournamentId={23}
        seasonId={63515}
      />

      <ServerComponent
        teamName="juventus"
        teamId={2687}
        tournamentId={23}
        seasonId={63515}
      />
      <ServerComponent
        teamName="arsenal"
        teamId={42}
        tournamentId={17}
        seasonId={61627}
      />
      <ServerComponent
        teamName="manutd"
        teamId={35}
        tournamentId={17}
        seasonId={61627}
      />
      <ServerComponent
        teamName="chelsea"
        teamId={38}
        tournamentId={17}
        seasonId={61627}
      />
      <ServerComponent
        teamName="manutd"
        teamId={35}
        tournamentId={17}
        seasonId={61627}
      />
      <ServerComponent
        teamName="psg"
        teamId={1644}
        tournamentId={34}
        seasonId={61736}
      />
      <ServerComponent
        teamName="bayern"
        teamId={2672}
        tournamentId={35}
        seasonId={63516}
      />
      <ServerComponent
        teamName="dortmund"
        teamId={2673}
        tournamentId={35}
        seasonId={63516}
      />
      <ServerComponent
        teamName="bayer"
        teamId={2681}
        tournamentId={35}
        seasonId={63516}
      />
    </>
  );
}
